// Central seed data for Yatra Setu (plain ESM so scripts can import it too)

export const DESTINATIONS = [
  {
    slug: "rishikesh",
    name: "Rishikesh",
    state: "Uttarakhand",
    tagline: "Adventure & Spirituality",
    categories: ["Adventure", "Spiritual", "Nature"],
    lat: 30.0869, lng: 78.2676,
    rating: 4.7, reviews: 2140,
    desc: "Yoga capital of the world on the banks of the Ganga. World-class white-water rafting, cliff jumps, bungee jumps, evening Ganga aarti at Triveni Ghat and Beatles-era ashrams.",
    best_time: "Sep – Nov",
    budget: "₹8,000 – ₹18,000",
    travel_mode: "Train / Bus to Dehradun, then 45 min taxi",
    images: [
      "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Ganga Aarti at Triveni Ghat", type: "Spiritual", price: 0, price_label: "Free", dur: "1 hr", desc: "Thousands of lamps floated on the Ganga at sunset, bells and chants.", img: "https://images.unsplash.com/photo-1609920658906-8223bd289001?auto=format&fit=crop&w=800&q=80" },
      { title: "White-water Rafting – 16 km", type: "Adventure", price: 1200, price_label: "₹1,200", dur: "3 hrs", desc: "Grade III+ rapids from Shivpuri with certified instructors.", img: "https://images.unsplash.com/photo-1530866495561-507c9faab2ed?auto=format&fit=crop&w=800&q=80" },
      { title: "Sunrise Trek to Kunjapuri Temple", type: "Adventure", price: 800, price_label: "₹800", dur: "5 hrs", desc: "360° Himalayan sunrise over the Swargashram valley.", img: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?auto=format&fit=crop&w=800&q=80" },
      { title: "Cook with a Garhwali Family", type: "Food", price: 500, price_label: "₹500", dur: "2 hrs", desc: "Learn aloo ke gutke and bal mithai in a local home kitchen.", img: "https://images.unsplash.com/photo-1556910103-1c02745aae4d?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "jaipur",
    name: "Jaipur",
    state: "Rajasthan",
    tagline: "Heritage & Culture",
    categories: ["Heritage", "Culture"],
    lat: 26.9124, lng: 75.7873,
    rating: 4.8, reviews: 3200,
    desc: "The Pink City — Hawa Mahal, Amber Fort, the bazaars of Johari and Bapu, block-printing workshops and rooftop thalis with a fort view.",
    best_time: "Oct – Mar",
    budget: "₹10,000 – ₹25,000",
    travel_mode: "Direct flights & trains from all metros",
    images: [
      "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Amber Fort at Golden Hour", type: "Heritage", price: 700, price_label: "₹700", dur: "3 hrs", desc: "Sheesh Mahal mirrors lit by the setting sun, then a light-and-sound show.", img: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80" },
      { title: "Old-City Food Walk", type: "Food", price: 900, price_label: "₹900", dur: "3 hrs", desc: "Pyaaz kachori, lassi in clay kulhads and ghewar through lanes locals actually eat in.", img: "https://images.unsplash.com/photo-1504674900247-0877df9cc836?auto=format&fit=crop&w=800&q=80" },
      { title: "Block-printing Workshop in Sanganer", type: "Culture", price: 1100, price_label: "₹1,100", dur: "2.5 hrs", desc: "Print your own scarf with third-generation artisans.", img: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "goa",
    name: "Goa",
    state: "Goa",
    tagline: "Beaches & Relaxation",
    categories: ["Beaches", "Nature"],
    lat: 15.2993, lng: 74.124,
    rating: 4.6, reviews: 5400,
    desc: "Beyond the party strip: silent discos, spice farms, Portuguese-quarter walks in Fontainhas, dolphin-spotting at dawn and beach shacks with fresh catch.",
    best_time: "Nov – Feb",
    budget: "₹12,000 – ₹28,000",
    travel_mode: "Fly to Dabolim / Mopa, or the Konkan Railway",
    images: [
      "https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Fontainhas Heritage Walk", type: "Culture", price: 600, price_label: "₹600", dur: "2 hrs", desc: "Latin-quarter lanes, bakeries and azulejo tiles with a Goan storyteller.", img: "https://images.unsplash.com/photo-1516483638261-f4dbaf036963?auto=format&fit=crop&w=800&q=80" },
      { title: "Sunset Cruise on the Mandovi", type: "Nature", price: 800, price_label: "₹800", dur: "2 hrs", desc: "Dolphins at the river mouth, live Goan mando music on deck.", img: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80" },
      { title: "Spice Farm Tour + Goan Thali", type: "Food", price: 950, price_label: "₹950", dur: "4 hrs", desc: "Cashew feni distillation, pepper vines and xacuti on a banana leaf.", img: "https://images.unsplash.com/photo-1509358271058-acd22cc93898?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "ladakh",
    name: "Ladakh",
    state: "Ladakh (UT)",
    tagline: "Mountains & Adventure",
    categories: ["Mountains", "Adventure"],
    lat: 34.1526, lng: 77.5771,
    rating: 4.9, reviews: 1870,
    desc: "High-altitude desert of turquoise lakes and moonscapes. Pangong Tso, Nubra's dunes, ancient gompas and the world's highest motorable passes.",
    best_time: "May – Sep",
    budget: "₹20,000 – ₹45,000",
    travel_mode: "Fly to Leh; acclimatise 2 days before roads",
    images: [
      "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Pangong Tso Day Trip", type: "Adventure", price: 3500, price_label: "₹3,500", dur: "14 hrs", desc: "Chang La pass, three Spangmik viewpoints and lakeside chai with Changpa nomads.", img: "https://images.unsplash.com/photo-1516426122078-c23e76319801?auto=format&fit=crop&w=800&q=80" },
      { title: "Thiksey Monastery Morning Prayers", type: "Spiritual", price: 0, price_label: "Free", dur: "2 hrs", desc: "Dawn horns and butter-lamp light with the monks of Thiksey gompa.", img: "https://images.unsplash.com/photo-1519821172144-4f87d85de2a1?auto=format&fit=crop&w=800&q=80" },
      { title: "Sham Valley Villages E-bike Loop", type: "Nature", price: 2800, price_label: "₹2,800", dur: "8 hrs", desc: "Magnetic Hill, the Sangam confluence and Basgo ruins on silent e-bikes.", img: "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "udaipur",
    name: "Udaipur",
    state: "Rajasthan",
    tagline: "Lakes & Romance",
    categories: ["Heritage", "Nature", "Culture"],
    lat: 24.5854, lng: 73.7125,
    rating: 4.8, reviews: 2600,
    desc: "The City of Lakes: City Palace courtyards, Lake Pichola sunsets, miniature-painting ateliers and the Aravalli foothills.",
    best_time: "Sep – Mar",
    budget: "₹12,000 – ₹30,000",
    travel_mode: "Fly to Udaipur or overnight train from Delhi",
    images: [
      "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1477587458883-47145ed94245?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Lake Pichola Sunset Boat Ride", type: "Nature", price: 700, price_label: "₹700", dur: "1.5 hrs", desc: "Jag Mandir and the Aravallis turning gold around you.", img: "https://images.unsplash.com/photo-1524492412937-b28074a5d7da?auto=format&fit=crop&w=800&q=80" },
      { title: "Miniature Painting Atelier", type: "Culture", price: 900, price_label: "₹900", dur: "2 hrs", desc: "Squirrel-hair brushes and single-hair strokes with a master artist.", img: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80" },
      { title: "Kumbhalgarh Day Trip", type: "Heritage", price: 2400, price_label: "₹2,400", dur: "9 hrs", desc: "The Great Wall of India, 36 km of ramparts in the Aravallis.", img: "https://images.unsplash.com/photo-1599661046289-e31897846e41?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "kashmir",
    name: "Kashmir",
    state: "Jammu & Kashmir",
    tagline: "Paradise on Earth",
    categories: ["Mountains", "Nature", "Adventure"],
    lat: 34.0837, lng: 74.7973,
    rating: 4.8, reviews: 2300,
    desc: "Snow-capped mountains, pristine lakes, lush valleys, shikara rides on Dal Lake and warm Kashmiri hospitality — India's alpine crown.",
    best_time: "Mar – Oct",
    budget: "₹15,000 – ₹35,000",
    travel_mode: "Fly to Srinagar; road transfers to Gulmarg / Pahalgam",
    images: [
      "https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Shikara Ride on Dal Lake", type: "Nature", price: 1000, price_label: "₹1,000", dur: "2 hrs", desc: "Floating gardens, wooden markets and sunset over Zabarwan hills.", img: "https://images.unsplash.com/photo-1566837945700-30057527ade0?auto=format&fit=crop&w=800&q=80" },
      { title: "Gulmarg Gondola & Snow", type: "Adventure", price: 2500, price_label: "₹2,500", dur: "Full day", desc: "One of the world's highest cable cars to Apharwat's snowfields.", img: "https://images.unsplash.com/photo-1551524559-8af4e6624178?auto=format&fit=crop&w=800&q=80" },
      { title: "Sonamarg Valley Trip", type: "Nature", price: 1800, price_label: "₹1,800", dur: "1 day", desc: "Meadow of gold, Thajiwas glacier and the Sindh river.", img: "https://images.unsplash.com/photo-1548013146-72479768bada?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "kerala",
    name: "Kerala",
    state: "Kerala",
    tagline: "God's Own Country",
    categories: ["Nature", "Wellness"],
    lat: 9.9312, lng: 76.2673,
    rating: 4.9, reviews: 4100,
    desc: "Emerald backwaters, houseboat nights under the stars, Ayurvedic retreats, tea-estate trails in Munnar and some of India's best food.",
    best_time: "Sep – Mar",
    budget: "₹14,000 – ₹32,000",
    travel_mode: "Fly to Kochi; trains along the coast",
    images: [
      "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Overnight Backwater Houseboat", type: "Nature", price: 6500, price_label: "₹6,500", dur: "Overnight", desc: "Drift the Alleppey canals; karimeen curry on board.", img: "https://images.unsplash.com/photo-1552733407-5d5c46c3bb3b?auto=format&fit=crop&w=800&q=80" },
      { title: "Munnar Tea-estate Cycle Trail", type: "Adventure", price: 1200, price_label: "₹1,200", dur: "4 hrs", desc: "Rolling green carpet hills, waterfalls and a tea-tasting finish.", img: "https://images.unsplash.com/photo-1593693411515-c20261bcad6e?auto=format&fit=crop&w=800&q=80" },
      { title: "Ayurvedic Wellness Day", type: "Wellness", price: 2200, price_label: "₹2,200", dur: "5 hrs", desc: "Abhyanga massage, shirodhara and a sattvic lunch.", img: "https://images.unsplash.com/photo-1545205597-3d9d02c29597?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "hampi",
    name: "Hampi",
    state: "Karnataka",
    tagline: "Boulders & Ruins",
    categories: ["Heritage", "Adventure"],
    lat: 15.335, lng: 76.46,
    rating: 4.7, reviews: 1900,
    desc: "The fallen Vijayanagara empire scattered across a boulder-strewn moonscape — coracle rides, rooftop cafés and sunrise at Matanga Hill.",
    best_time: "Oct – Feb",
    budget: "₹8,000 – ₹16,000",
    travel_mode: "Overnight train to Hospet, then 30 min tuk-tuk",
    images: [
      "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Sunrise at Matanga Hill", type: "Adventure", price: 600, price_label: "₹600", dur: "3 hrs", desc: "A 45-min scramble for the entire ruin-scape turning gold.", img: "https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?auto=format&fit=crop&w=800&q=80" },
      { title: "Coracle Ride on the Tungabhadra", type: "Nature", price: 400, price_label: "₹400", dur: "1 hr", desc: "Round basket-boats across crocodile-haunted waters (safe, promise).", img: "https://images.unsplash.com/photo-1564507592333-c60657eea523?auto=format&fit=crop&w=800&q=80" },
      { title: "Cycling the Royal Enclosure", type: "Heritage", price: 500, price_label: "₹500", dur: "4 hrs", desc: "Vittala Temple's musical pillars and the stone chariot by cycle.", img: "https://images.unsplash.com/photo-1488646953014-85cb44e25828?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "meghalaya",
    name: "Meghalaya",
    state: "Meghalaya",
    tagline: "Abode of Clouds",
    categories: ["Nature", "Adventure"],
    lat: 25.467, lng: 91.3662,
    rating: 4.8, reviews: 1100,
    desc: "Living root bridges, the rain-soaked cliffs of Cherrapunji, crystal-clear Umngot river and Asia's cleanest village, Mawlynnong.",
    best_time: "Oct – Apr",
    budget: "₹12,000 – ₹24,000",
    travel_mode: "Fly to Guwahati, then 3 hr drive to Shillong",
    images: [
      "https://images.unsplash.com/photo-1598887142487-3c854d51eabb?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1502085671122-2d218cd434e6?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Double-Decker Root Bridge Trek", type: "Adventure", price: 1500, price_label: "₹1,500", dur: "7 hrs", desc: "3,500 steps each way to a bridge grown, not built.", img: "https://images.unsplash.com/photo-1598887142487-3c854d51eabb?auto=format&fit=crop&w=800&q=80" },
      { title: "Boating on the Umngot", type: "Nature", price: 800, price_label: "₹800", dur: "2 hrs", desc: "Glass-clear river at Dawki — boats seem to float on air.", img: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80" },
      { title: "Mawlynnong & Sky View", type: "Culture", price: 900, price_label: "₹900", dur: "4 hrs", desc: "Asia's cleanest village and a bamboo skywalk to Bangladesh views.", img: "https://images.unsplash.com/photo-1502085671122-2d218cd434e6?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "varanasi",
    name: "Varanasi",
    state: "Uttar Pradesh",
    tagline: "Eternal City",
    categories: ["Spiritual", "Culture", "Heritage"],
    lat: 25.3176, lng: 82.9739,
    rating: 4.7, reviews: 3800,
    desc: "The world's oldest living city: dawn boat rides past 84 ghats, the deafening beauty of Ganga aarti at Dashashwamedh, silk weavers' lanes.",
    best_time: "Oct – Mar",
    budget: "₹7,000 – ₹15,000",
    travel_mode: "Direct trains & flights; arrive early morning",
    images: [
      "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1609920658906-8223bd289001?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Dawn Boat Ride past the Ghats", type: "Spiritual", price: 500, price_label: "₹500", dur: "1.5 hrs", desc: "Assi to Manikarnika as the city wakes into the light.", img: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80" },
      { title: "Ganga Aarti from a Rooftop", type: "Spiritual", price: 300, price_label: "₹300", dur: "1 hr", desc: "Fire, bells and conch shells — the best seat is a boat or rooftop.", img: "https://images.unsplash.com/photo-1561361513-2d000a50f0dc?auto=format&fit=crop&w=800&q=80" },
      { title: "Banarasi Silk Weaving Visit", type: "Culture", price: 700, price_label: "₹700", dur: "2 hrs", desc: "Meet handloom weavers keeping a 500-year craft alive.", img: "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "andaman",
    name: "Andaman Islands",
    state: "Andaman & Nicobar",
    tagline: "Turquoise Escape",
    categories: ["Beaches", "Adventure", "Nature"],
    lat: 11.7401, lng: 92.6586,
    rating: 4.8, reviews: 1500,
    desc: "Radhanagar's white sand, coral gardens at Elephant Beach, the sombre history of Cellular Jail and bioluminescent night kayaking.",
    best_time: "Oct – May",
    budget: "₹22,000 – ₹50,000",
    travel_mode: "Fly to Port Blair (via Chennai / Kolkata)",
    images: [
      "https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "Scuba at Elephant Beach", type: "Adventure", price: 3500, price_label: "₹3,500", dur: "3 hrs", desc: "Beginner dives over coral gardens with PADI instructors.", img: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80" },
      { title: "Radhanagar Beach Sunset", type: "Nature", price: 0, price_label: "Free", dur: "3 hrs", desc: "Asia's best beach — bring a book and stay till the sky burns.", img: "https://images.unsplash.com/photo-1512100356356-de1b84283e18?auto=format&fit=crop&w=800&q=80" },
      { title: "Bioluminescence Night Kayak", type: "Adventure", price: 2800, price_label: "₹2,800", dur: "2 hrs", desc: "Paddle through glowing plankton on new-moon nights.", img: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=800&q=80" },
    ],
  },
  {
    slug: "pondicherry",
    name: "Pondicherry",
    state: "Puducherry (UT)",
    tagline: "French Riviera of the East",
    categories: ["Beaches", "Culture", "Wellness"],
    lat: 11.9416, lng: 79.8083,
    rating: 4.5, reviews: 1700,
    desc: "Yellow-walled French quarters, cycling the Promenade at dawn, Auroville's golden globe and café culture with Tamil warmth.",
    best_time: "Oct – Mar",
    budget: "₹8,000 – ₹18,000",
    travel_mode: "3 hr drive from Chennai or the scenic Pondy Express",
    images: [
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1600&q=80",
      "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=1600&q=80",
    ],
    experiences: [
      { title: "White Town Cycle Tour", type: "Culture", price: 500, price_label: "₹500", dur: "2 hrs", desc: "Tamil–French architecture, bakeries and the sea wall at first light.", img: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80" },
      { title: "Auroville & Matrimandir", type: "Spiritual", price: 600, price_label: "₹600", dur: "4 hrs", desc: "The golden meditation dome and an experimental township's story.", img: "https://images.unsplash.com/photo-1519046904884-53103b34b206?auto=format&fit=crop&w=800&q=80" },
      { title: "Surf Lesson at Serenity Beach", type: "Adventure", price: 1200, price_label: "₹1,200", dur: "2 hrs", desc: "Gentle breaks, local surf shacks and sunscreen you'll regret forgetting.", img: "https://images.unsplash.com/photo-1502680390469-be75c86b636f?auto=format&fit=crop&w=800&q=80" },
    ],
  },
];

export const GUIDES = [
  { dest: "rishikesh", name: "Anand Rawat", img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80", langs: "Hindi, English, Garhwali", years: 9, fee: 1200, rating: 4.9, verified: true, tagline: "Rafting instructor turned mountain guide; grew up on these ghats." },
  { dest: "rishikesh", name: "Meera Joshi", img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=400&q=80", langs: "Hindi, English", years: 6, fee: 900, rating: 4.8, verified: true, tagline: "Yoga teacher who leads sunrise treks and ashram walks." },
  { dest: "jaipur", name: "Devendra Singh", img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80", langs: "Hindi, English, French", years: 12, fee: 1500, rating: 4.9, verified: true, tagline: "Third-generation Pink City storyteller; knows every haveli's secret." },
  { dest: "jaipur", name: "Priya Rathore", img: "https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=400&q=80", langs: "Hindi, English", years: 5, fee: 1000, rating: 4.7, verified: true, tagline: "Food historian — my food walks end at places Google can't find." },
  { dest: "goa", name: "Cajetan Fernandes", img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=400&q=80", langs: "Konkani, English, Hindi", years: 8, fee: 1100, rating: 4.8, verified: true, tagline: "Fontainhas-born; I'll show you Goa your taxi driver won't." },
  { dest: "goa", name: "Sanya Costa", img: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=400&q=80", langs: "English, Konkani", years: 4, fee: 900, rating: 4.6, verified: false, tagline: "Marine biology student leading dawn dolphin and spice-farm trips." },
  { dest: "ladakh", name: "Tsering Angmo", img: "https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&w=400&q=80", langs: "Ladakhi, Hindi, English", years: 10, fee: 2000, rating: 5.0, verified: true, tagline: "Leh local; high-altitude treks, monastery stays and homestays in Hemis." },
  { dest: "ladakh", name: "Stanzin Dorje", img: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&w=400&q=80", langs: "Ladakhi, Hindi, English", years: 7, fee: 1800, rating: 4.8, verified: true, tagline: "Bike mechanic and guide — Pangong and Nubra without the crowds." },
  { dest: "udaipur", name: "Kunal Chundawat", img: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=400&q=80", langs: "Hindi, English, Mewari", years: 11, fee: 1400, rating: 4.9, verified: true, tagline: "Ex-hotelier; palaces by day, hidden rooftop chai by night." },
  { dest: "kashmir", name: "Bashir Ahmad", img: "https://images.unsplash.com/photo-1531123897727-8f129e1688ce?auto=format&fit=crop&w=400&q=80", langs: "Kashmiri, Urdu, Hindi, English", years: 15, fee: 1600, rating: 4.9, verified: true, tagline: "Srinagar houseboat family; shikara, saffron fields and Wazwan." },
  { dest: "kashmir", name: "Nusrat Jan", img: "https://images.unsplash.com/photo-1552058544-f2b08422138a?auto=format&fit=crop&w=400&q=80", langs: "Kashmiri, Hindi, English", years: 6, fee: 1200, rating: 4.7, verified: true, tagline: "Gulmarg snow guide in winter, saffron-field host in autumn." },
  { dest: "kerala", name: "Rahul Menon", img: "https://images.unsplash.com/photo-1556157382-97eda2d62296?auto=format&fit=crop&w=400&q=80", langs: "Malayalam, English, Hindi", years: 8, fee: 1300, rating: 4.8, verified: true, tagline: "Backwater native — canoe lanes no houseboat can enter." },
  { dest: "kerala", name: "Lakshmi Iyer", img: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80", langs: "Malayalam, English, Tamil", years: 9, fee: 1100, rating: 4.8, verified: true, tagline: "Ayurveda practitioner; Munnar tea trails and sattvic food homes." },
  { dest: "hampi", name: "Girish Naik", img: "https://images.unsplash.com/photo-1508341591423-4347099e1f19?auto=format&fit=crop&w=400&q=80", langs: "Kannada, Hindi, English", years: 6, fee: 900, rating: 4.7, verified: false, tagline: "Boulder-climbing guide; my father helped excavate the site." },
  { dest: "meghalaya", name: "Pynshaibha Lyngdoh", img: "https://images.unsplash.com/photo-1531427186611-ecfd6d936c79?auto=format&fit=crop&w=400&q=80", langs: "Khasi, English, Hindi", years: 5, fee: 1000, rating: 4.8, verified: true, tagline: "Cherrapunji local; root-bridge treks with stories my grandmother told." },
  { dest: "varanasi", name: "Deendayal Pandey", img: "https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80", langs: "Hindi, English, Bhojpuri", years: 20, fee: 1000, rating: 4.9, verified: true, tagline: "Seventh-generation Banarasi; dawn boat rides and alley food legends." },
  { dest: "andaman", name: "Jhonny Barman", img: "https://images.unsplash.com/photo-1521119989659-a83eee488004?auto=format&fit=crop&w=400&q=80", langs: "Hindi, English, Bengali", years: 7, fee: 1500, rating: 4.7, verified: true, tagline: "Dive master at Havelock; reefs, shipwrecks and bioluminescence nights." },
  { dest: "pondicherry", name: "Anbumani Rajasekaran", img: "https://images.unsplash.com/photo-1568602471122-7832951cc4c5?auto=format&fit=crop&w=400&q=80", langs: "Tamil, French, English", years: 6, fee: 900, rating: 4.6, verified: true, tagline: "White Town born and bred — cycling tours with café stops." },
];

export const HOMESTAYS = [
  { dest: "rishikesh", name: "Ganga View Homestay", host: "Sunita Rawat", img: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=800&q=80", price: 1800, rating: 4.8, tagline: "Family home above Triveni Ghat; home-cooked Garhwali meals." },
  { dest: "rishikesh", name: "Forest Ashram Cottage", host: "Harish Bhatt", img: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&w=800&q=80", price: 1400, rating: 4.6, tagline: "Quiet mango-grove cottage 10 min from Lakshman Jhula." },
  { dest: "jaipur", name: "Haveli Kalwar", host: "Kiran Kanwar", img: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=800&q=80", price: 2600, rating: 4.9, tagline: "250-year-old haveli with frescoed courtyards in old Amer." },
  { dest: "goa", name: "Casa Susegad", host: "Mariana D'Souza", img: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?auto=format&fit=crop&w=800&q=80", price: 3200, rating: 4.8, tagline: "Portuguese-style villa in Assagao with a baker's breakfast." },
  { dest: "ladakh", name: "Hemis Homestay", host: "Tsering Dolker", img: "https://images.unsplash.com/photo-1570129477492-45c003edd2be?auto=format&fit=crop&w=800&q=80", price: 1500, rating: 4.9, tagline: "Traditional Ladakhi kitchen, butter tea and apricot orchards." },
  { dest: "udaipur", name: "Lake Rampart Room", host: "Bhairav Singh", img: "https://images.unsplash.com/photo-1564013799919-ab600027ffc6?auto=format&fit=crop&w=800&q=80", price: 2200, rating: 4.7, tagline: "Rooftop room facing Lake Pichola in a living Mewari home." },
  { dest: "kashmir", name: "Dal Gate Houseboat", host: "Bashir Ahmad", img: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80", price: 3800, rating: 4.8, tagline: "Cedar houseboat with carved balconies on Nigeen Lake." },
  { dest: "kerala", name: "Backwater Bread & Breakfast", host: "Meera Nair", img: "https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80", price: 2400, rating: 4.9, tagline: "Canal-side home in Alleppey; toddy-tapper's breakfast, canoe rides." },
  { dest: "kerala", name: "Munnar Cardamom Villa", host: "Shaji Kurien", img: "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=800&q=80", price: 2900, rating: 4.7, tagline: "Plantation bungalow wrapped in cardamom forest." },
  { dest: "hampi", name: "Boulder Garden Stay", host: "Gowri Kamat", img: "https://images.unsplash.com/photo-1521401830884-6c03c1c87ebb?auto=format&fit=crop&w=800&q=80", price: 1300, rating: 4.6, tagline: "Mango-grove hut with hammocks, 5 min from the Virupaksha bazaar." },
  { dest: "meghalaya", name: "Mawlynnong Clean Village Home", host: "Ibansara Kharmawphlang", img: "https://images.unsplash.com/photo-1518780664697-55e3ad937233?auto=format&fit=crop&w=800&q=80", price: 1600, rating: 4.8, tagline: "Bamboo home in Asia's cleanest village; Khasi family dinners." },
  { dest: "varanasi", name: "Ghat Ki Haveli", host: "Deendayal Pandey", img: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?auto=format&fit=crop&w=800&q=80", price: 1700, rating: 4.7, tagline: "300-year-old home on Narad Ghat; wake to temple bells." },
  { dest: "andaman", name: "Havelock Palm Grove", host: "Jhonny Barman", img: "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=800&q=80", price: 2800, rating: 4.7, tagline: "Beachfront grove cottages, 400 m from Radhanagar." },
  { dest: "pondicherry", name: "Villa Chi Whitetown", host: "Sophie Ramanujam", img: "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=800&q=80", price: 3000, rating: 4.8, tagline: "French-quarter townhouse with a courtyard café downstairs." },
];

export const REVIEWS = [
  { dest: "rishikesh", uid: 1, name: "Aarav Sharma", rating: 5, text: "Anand's rafting run was the highlight of our year. This platform connected us straight to him — no middleman markup." },
  { dest: "rishikesh", uid: null, name: "Ishita Verma", rating: 4, text: "Stayed at Ganga View Homestay. Sunita aunty's food alone is worth the trip. Wi-Fi is patchy though." },
  { dest: "jaipur", uid: 1, name: "Aarav Sharma", rating: 5, text: "Devendra knows walls that don't appear on any map. The Sanganer printing workshop was a highlight." },
  { dest: "jaipur", uid: null, name: "Rohan Gupta", rating: 5, text: "The food walk with Priya — kachori, kulhad lassi, ghewar — best ₹900 I've spent in India." },
  { dest: "goa", uid: null, name: "Farah Khan", rating: 4, text: "Fontainhas walk felt like old Lisbon. Cajetan's stories make the lanes come alive." },
  { dest: "ladakh", uid: 1, name: "Aarav Sharma", rating: 5, text: "Tsering arranged everything — permits, oxygen, homestay in Hemis. Felt like travelling with family." },
  { dest: "kashmir", uid: null, name: "Kabir Malhotra", rating: 5, text: "Bashir's houseboat is even better than the photos. Gulmarg gondola tickets he got us at local price." },
  { dest: "kashmir", uid: 1, name: "Aarav Sharma", rating: 5, text: "Sonamarg in September with almost no crowds. Nusrat knew exactly when the light hits Thajiwas." },
  { dest: "kerala", uid: null, name: "Ananya Pillai", rating: 5, text: "Meera's homestay + Rahul's canoe lanes = the real Alleppey. Skipped the big houseboats, no regrets." },
  { dest: "kerala", uid: null, name: "Vikram Rao", rating: 4, text: "Lakshmi's Ayurveda day reset my sleep cycle for weeks. Munnar cycling is moderately tough — worth it." },
  { dest: "hampi", uid: null, name: "Tanvi Desai", rating: 5, text: "Sunrise from Matanga with Girish — he showed us the excavation stories his father worked on. Magic." },
  { dest: "meghalaya", uid: 1, name: "Aarav Sharma", rating: 5, text: "The root-bridge trek is 3,500 steps of wonder. Pynshaibha's grandmother stories made it unforgettable." },
  { dest: "varanasi", uid: null, name: "Nikhil Joshi", rating: 5, text: "Deendayal-ji's dawn boat ride and the alley food crawl. Varanasi through a local's eyes, exactly as promised." },
  { dest: "andaman", uid: null, name: "Sara Thomas", rating: 5, text: "First scuba dive with Jhonny — patient, safety-first, and the reef is unreal. Night kayak was pure magic." },
  { dest: "pondicherry", uid: 1, name: "Aarav Sharma", rating: 4, text: "Anbumani's cycle tour + croissants at Baker Street. Auroville visit needs advance booking, plan ahead." },
];

export const DEMO_USERS = [
  { name: "Aarav Sharma", email: "aarav@demo.in", password: "demo1234", role: "traveler", city: "Delhi", phone: "98100 12345" },
  { name: "Meera Nair", email: "meera@demo.in", password: "demo1234", role: "host", city: "Alleppey", phone: "98470 22334" },
  { name: "Tsering Angmo", email: "tsering@demo.in", password: "demo1234", role: "host", city: "Leh", phone: "99069 85521" },
];

// Itinerary templates used by the Plan Trip wizard (per-destination day plans)
export const TRIP_TEMPLATES = {
  rishikesh: ["Ganga Aarti at Triveni Ghat", "White-water Rafting – 16 km", "Sunrise Trek to Kunjapuri Temple"],
  jaipur: ["Amber Fort at Golden Hour", "Old-City Food Walk", "Block-printing Workshop in Sanganer"],
  goa: ["Fontainhas Heritage Walk", "Sunset Cruise on the Mandovi", "Spice Farm Tour + Goan Thali"],
  ladakh: ["Thiksey Monastery Morning Prayers", "Pangong Tso Day Trip", "Sham Valley Villages E-bike Loop"],
  udaipur: ["Lake Pichola Sunset Boat Ride", "Miniature Painting Atelier", "Kumbhalgarh Day Trip"],
  kashmir: ["Shikara Ride on Dal Lake", "Gulmarg Gondola & Snow", "Sonamarg Valley Trip"],
  kerala: ["Overnight Backwater Houseboat", "Munnar Tea-estate Cycle Trail", "Ayurvedic Wellness Day"],
  hampi: ["Sunrise at Matanga Hill", "Coracle Ride on the Tungabhadra", "Cycling the Royal Enclosure"],
  meghalaya: ["Double-Decker Root Bridge Trek", "Boating on the Umngot", "Mawlynnong & Sky View"],
  varanasi: ["Dawn Boat Ride past the Ghats", "Ganga Aarti from a Rooftop", "Banarasi Silk Weaving Visit"],
  andaman: ["Radhanagar Beach Sunset", "Scuba at Elephant Beach", "Bioluminescence Night Kayak"],
  pondicherry: ["White Town Cycle Tour", "Auroville & Matrimandir", "Surf Lesson at Serenity Beach"],
};
